feat: port the admon plugin
executablebooks/mdit-py-plugins pull request #53
Opened 2022-11-26 15:12 UTC by KyleKing

I had two hours this morning and tried porting the plugin! It passes all tests locally and seems to work, but I'll take another look through tomorrow to make sure it is merge-ready. I'm opening a PR for now, since there seemed to be a couple of people interested, and I would benefit from any feedback.

2022-11-26 15:16 UTC, KyleKing commented on mdit_py_plugins/admon/LICENSE
> +Permission is hereby granted, free of charge, to any person
TBD: What license goes here?

2022-11-26 15:16 UTC, KyleKing commented on mdit_py_plugins/admon/index.py
> +    return bool(tag)
TBD: How strict should the validation be? The original JS plugin didn't check against the list of tags

2022-11-26 15:16 UTC, KyleKing commented on mdit_py_plugins/admon/index.py
> +    md.block.ruler.before(
TBD: the original plugin had options, and I'll need to follow up to see how to port those. For reference:

https://github.com/commenthol/markdown-it-admon/blob/9820ba89415c464a3cc18a780f222a0ceb3e18bd/index.js#L164-L170

2022-11-27 13:57 UTC, KyleKing commented
I think this is now ready for review. Let me know if there is anything that needs to be modified, and I would be happy to make those changes, or feel free to go ahead and make changes directly!

Based [on this recommendation](https://github.com/executablebooks/mdformat/issues/309#issuecomment-1046327823), this PR ports this JS plugin to Python: https://github.com/commenthol/markdown-it-admon/blob/9820ba89415c464a3cc18a780f222a0ceb3e18bd/index.js

2022-11-28 12:30 UTC, hukkin requested changes
Thanks! This seems good to me assuming that tests pass.

Would @chrisjsewell be able to approve CI and review too?

2022-11-28 13:09 UTC, KyleKing commented on mdit_py_plugins/admon/port.yaml
> +  date: Nov 26, 2022
Makes sense to me!

```suggestion
  date: Jul 3, 2021
```

2022-12-01 16:17 UTC, hukkin commented
Regarding broken CI checks:
- both failures unrelated to this PR
- pre-commit check should be fixed by https://github.com/executablebooks/mdit-py-plugins/pull/54

2022-12-05 10:21 UTC, chrisjsewell requested changes

2022-12-05 10:21 UTC, chrisjsewell commented on mdit_py_plugins/admon/index.py
> +# ]
if this is not used, then I would just delete it

2022-12-05 10:21 UTC, chrisjsewell commented on mdit_py_plugins/admon/index.py
> +def admonition(state: StateBlock, startLine: int, endLine: int, silent: bool):
```suggestion
def admonition(state: StateBlock, startLine: int, endLine: int, silent: bool) -> bool:
```

2022-12-05 12:24 UTC, KyleKing commented
Thanks for the feedback! I think I made all the requested changes. Let me know if there is anything else.

For coverage, is 100% statement coverage expected? There are a few that aren't tested, but they are only one lines returns like `return True` or `return "", ""`

2022-12-05 12:31 UTC, chrisjsewell commented
@hukkin do you want to approve before I merge ta

2022-12-05 15:02 UTC, merged